name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run EDS Script
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
        run: node scripts/scripts.js
        

